name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  run:
    name: Node.js ${{ matrix.node }} @ ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [10, 12, 13, 14]
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - run: node --version
      - run: npm --version

      - name: Install npm dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci
